### ISSUE TITLE
Mehr Platz für Modding Schneidwerk 

### ISSUE THREAD

**Issue by Koenigsboa** [Achimobil/FS22_RopaStorage#2]
Hallo
Wenn du das Schneidwerklager für den LS25 raus bringst, wäre es möglich die Schächte tiefer zu machen?
Das wäre für Schneidwerke die man nicht einklappen kann toll.

**Comment by Achimobil** [comment]
Ich denke nicht. den das Lager ist für diese Speziellen Schneidwerke und da sollen keine anderen drauf.
Ob ich dir überhaupt machen werden ist aber eher die Frage, den dazu muss ja erst mal bedarf da sein und da weiß noch keiner ob es den geben wird.
